---
lake:
  encryptionSecret:
    secretName: konflux-devlake-secrets
    autoCreateSecret: false
  securityContext: {}
  containerSecurityContext: {}
  envs:
    REMOTE_PLUGIN_DIR: ""
    DISABLED_REMOTE_PLUGINS: "true"
    API_REQUESTS_PER_HOUR: "100000"
    LOGGING_DIR: "/tmp"
  envFrom:
    - secretRef:
        name: konflux-devlake-secrets

mysql:
  useExternal: true
  externalServer: "kubernetes.default.svc.cluster.local"  # K8s API - always available
  externalPort: 443  # HTTPS port - always open

grafana:
  image:
    repository: devlake.docker.scarf.sh/apache/devlake-dashboard
    tag: v1.0.2
  podSecurityContext: {}
  securityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null
  initChownData:
    enabled: false
  envFromSecrets:
    - name: "konflux-devlake-secrets"
  env:
    TZ: "UTC"
    GF_SERVER_SERVE_FROM_SUBPATH: "true"
  grafana.ini:
    server:
      serve_from_subpath: "true"
      root_url: "https://konflux-devlake-ui-konflux-devlake.apps.rosa.gzqkd-6tm9g-h9c.jryo.p3.openshiftapps.com/grafana/"
      domain: "konflux-devlake-ui-konflux-devlake.apps.rosa.gzqkd-6tm9g-h9c.jryo.p3.openshiftapps.com"
    auth.google:
      enabled: true
      client_id: "${GF_AUTH_GOOGLE_CLIENT_ID}"  # Set via secret
      client_secret: "${GF_AUTH_GOOGLE_CLIENT_SECRET}"  # Set via secret
      scopes: "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email openid"
      auth_url: "https://accounts.google.com/o/oauth2/v2/auth"
      token_url: "https://oauth2.googleapis.com/token"
      api_url: "https://openidconnect.googleapis.com/v1/userinfo"
      allowed_domains: "redhat.com"
      allow_sign_up: true
      auto_login: true
      redirect_uri: "https://konflux-devlake-ui-konflux-devlake.apps.rosa.gzqkd-6tm9g-h9c.jryo.p3.openshiftapps.com/grafana/login/google"
ui:
  securityContext: {}
  containerSecurityContext: {}
  basicAuth:
    enabled: false
    autoCreateSecret: true
    secretName: ""

service:
  type: ClusterIP

ingress:
  enabled: false

option:
  autoCreateSecret: false
  database: mysql
  connectionSecretName: "konflux-devlake-secrets"

extraResources:
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: konflux-devlake-ui
    spec:
      to:
        kind: Service
        name: konflux-devlake-ui
        weight: 100
      port:
        targetPort: ui
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
