---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: konflux-devlake

resources:
- ../base
- external-secrets
- https://github.com/konflux-ci/konflux-devlake-mcp.git/k8s?ref=ade23c78280fa9614437df2a2b2ed3dccc38b253

helmCharts:
- name: devlake
  repo: https://apache.github.io/incubator-devlake-helm-chart
  version: 1.0.2
  releaseName: konflux-devlake
  namespace: konflux-devlake
  valuesFile: helm-values.yaml
  includeCRDs: true

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
